services:
  postgres:
    image: docker.io/library/postgres:latest
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build:
      context: .
    command: bash bin/dev
    working_dir: /app
    volumes:
      - bundledata:/usr/local/bundle
      - .:/app
    ports:
      - "3000:3000"

    environment:
      LANG: ${LANG}
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      PORT: 3000

    depends_on:
      - postgres

volumes:
  postgresdata:
  bundledata:
